services:
  - type: web
    name: twitter-clone
    env: php
    plan: free
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: php -S 0.0.0.0:10000 -t public
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_NAME
        value: twitter_clone
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: ""
